In [2]:
import pandas as pd
import pickle
from mlxtend.frequent_patterns import association_rules

## Pattern mining on purchases and different sections

This section of the analysis aims to show the most frequent patterns in purchase products of different sections in the same session. The purpose for this is to show a link to a particular section when the user adds to the basket a product of another section, in order to push the user to buy more products.

In [19]:
with open("frequent_purchase_section_2.pkl", "rb") as f:  # "rb" = read binary
    s_purchases = pickle.load(f)

s_purchases = pd.DataFrame(s_purchases)

print("Number of frequent sections")
print(len(s_purchases))

Number of frequent sections
141

In [45]:
s_purchases_rules = association_rules(s_purchases, metric="confidence", min_threshold=0.3)
s_purchases_rules = s_purchases_rules[["antecedents", "consequents", "antecedent support",
                                       "consequent support", "support", "confidence", "lift"]]

print("Association rules with minimum confidence level set to 0.3")
s_purchases_rules

Association rules with minimum confidence level set to 0.3

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift
0,"frozenset({ computers, accessories})",frozenset({ appliances}),0.005587,0.436083,0.002456,0.439573,1.008003
1,"frozenset({ accessories, appliances})",frozenset({ computers}),0.006463,0.350288,0.002456,0.379981,1.084767
2,"frozenset({ accessories, electronics})",frozenset({ computers}),0.003549,0.350288,0.001193,0.336283,0.960020
3,"frozenset({ accessories, electronics})",frozenset({ appliances}),0.003549,0.436083,0.001278,0.360177,0.825937
4,frozenset({ electronics}),frozenset({ appliances}),0.123306,0.436083,0.040101,0.325218,0.745770
...,...,...,...,...,...,...,...
78,"frozenset({ construction, sport})",frozenset({ computers}),0.007154,0.350288,0.002453,0.342845,0.978752
79,"frozenset({ computers, construction, sport})",frozenset({ appliances}),0.002453,0.436083,0.001482,0.604353,1.385868
80,"frozenset({ construction, sport, appliances})",frozenset({ computers}),0.003332,0.350288,0.001482,0.444863,1.269994
81,"frozenset({ construction, country_yard})",frozenset({ appliances}),0.009069,0.436083,0.005555,0.612535,1.404629
82,"frozenset({ computers, construction, country...",frozenset({ appliances}),0.001765,0.436083,0.001156,0.654804,1.501559

Using confidence as threshold value to determine the best association rules is not so reliable in this situation. This is because there are some sections (particularly "appliances" and "computers") with a really high support. The computation of confidence takes into account only how frequent the antecedent is, causing an inflation of the measure. This can also be seen when looking at the lift, which for some rules is even below 1. This is why, in this situation, is much more better to compute association rules using a minimum lift threshold.

In [ ]:
s_purchases_rules = association_rules(s_purchases, metric="lift", min_threshold=2)
s_purchases_rules = s_purchases_rules[["antecedents", "consequents", "antecedent support",
                                       "consequent support", "support", "confidence", "lift"]]

print("Association rules with minimum lift level set to 2")
s_purchases_rules

Association rules with minimum confidence level set to 0.3

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,"frozenset({ computers, electronics})","frozenset({ sport, appliances})",0.034643,0.043367,0.003505,0.101160,2.332649,1.0,0.002002,1.064297,0.591805,0.047037,0.060413,0.090986
1,"frozenset({ computers, sport})","frozenset({ electronics, appliances})",0.039282,0.040101,0.003505,0.089216,2.224763,1.0,0.001929,1.053926,0.573023,0.046186,0.051166,0.088304
2,"frozenset({ computers, appliances})","frozenset({ electronics, sport})",0.104244,0.013089,0.003505,0.033619,2.568525,1.0,0.002140,1.021244,0.681739,0.030788,0.020802,0.150686
3,"frozenset({ electronics, sport})","frozenset({ computers, appliances})",0.013089,0.104244,0.003505,0.267754,2.568525,1.0,0.002140,1.223299,0.618770,0.030788,0.182539,0.150686
4,"frozenset({ electronics, appliances})","frozenset({ computers, sport})",0.040101,0.039282,0.003505,0.087392,2.224763,1.0,0.001929,1.052718,0.573513,0.046186,0.050078,0.088304
5,"frozenset({ sport, appliances})","frozenset({ computers, electronics})",0.043367,0.034643,0.003505,0.080811,2.332649,1.0,0.002002,1.050226,0.597202,0.047037,0.047824,0.090986
6,"frozenset({ computers, appliances})","frozenset({ sport, furniture})",0.104244,0.005618,0.001394,0.013375,2.380784,1.0,0.000809,1.007862,0.647465,0.012854,0.007801,0.130779
7,"frozenset({ computers, sport})","frozenset({ furniture, appliances})",0.039282,0.017586,0.001394,0.035494,2.018392,1.0,0.000703,1.018568,0.525186,0.025134,0.018230,0.057390
8,"frozenset({ furniture, appliances})","frozenset({ computers, sport})",0.017586,0.039282,0.001394,0.079286,2.018392,1.0,0.000703,1.043449,0.513588,0.025134,0.041640,0.057390
9,"frozenset({ sport, furniture})","frozenset({ computers, appliances})",0.005618,0.104244,0.001394,0.248183,2.380784,1.0,0.000809,1.191455,0.583247,0.012854,0.160690,0.130779
10,"frozenset({ computers, electronics})","frozenset({ furniture, appliances})",0.034643,0.017586,0.001445,0.041697,2.371093,1.0,0.000835,1.025160,0.599005,0.028444,0.024543,0.061920
11,"frozenset({ computers, appliances})","frozenset({ electronics, furniture})",0.104244,0.005637,0.001445,0.013857,2.458333,1.0,0.000857,1.008336,0.662257,0.013321,0.008267,0.135062
12,"frozenset({ computers, furniture})","frozenset({ electronics, appliances})",0.017538,0.040101,0.001445,0.082363,2.053888,1.0,0.000741,1.046056,0.522279,0.025706,0.044028,0.059193
13,"frozenset({ electronics, appliances})","frozenset({ computers, furniture})",0.040101,0.017538,0.001445,0.036022,2.053888,1.0,0.000741,1.019174,0.534555,0.025706,0.018813,0.059193
14,"frozenset({ electronics, furniture})","frozenset({ computers, appliances})",0.005637,0.104244,0.001445,0.256267,2.458333,1.0,0.000857,1.204405,0.596583,0.013321,0.169715,0.135062
15,"frozenset({ furniture, appliances})","frozenset({ computers, electronics})",0.017586,0.034643,0.001445,0.082143,2.371093,1.0,0.000835,1.051750,0.588605,0.028444,0.049204,0.061920
16,"frozenset({ computers, electronics, applianc...",frozenset({ medicine}),0.016647,0.053695,0.001878,0.112809,2.100902,1.0,0.000984,1.066630,0.532885,0.027429,0.062468,0.073891
17,"frozenset({ computers, electronics})","frozenset({ medicine, appliances})",0.034643,0.020741,0.001878,0.054206,2.613408,1.0,0.001159,1.035382,0.639513,0.035096,0.034173,0.072372
18,"frozenset({ computers, medicine})","frozenset({ electronics, appliances})",0.016800,0.040101,0.001878,0.111776,2.787338,1.0,0.001204,1.080694,0.652192,0.034129,0.074669,0.079302
19,"frozenset({ computers, appliances})","frozenset({ electronics, medicine})",0.104244,0.007675,0.001878,0.018014,2.347185,1.0,0.001078,1.010529,0.640753,0.017065,0.010419,0.131348
20,"frozenset({ electronics, medicine})","frozenset({ computers, appliances})",0.007675,0.104244,0.001878,0.244681,2.347185,1.0,0.001078,1.185930,0.578397,0.017065,0.156780,0.131348
21,"frozenset({ electronics, appliances})","frozenset({ computers, medicine})",0.040101,0.016800,0.001878,0.046829,2.787338,1.0,0.001204,1.031503,0.668023,0.034129,0.030541,0.079302
22,"frozenset({ medicine, appliances})","frozenset({ computers, electronics})",0.020741,0.034643,0.001878,0.090537,2.613408,1.0,0.001159,1.061458,0.630434,0.035096,0.057900,0.072372
23,frozenset({ medicine}),"frozenset({ computers, electronics, applianc...",0.053695,0.016647,0.001878,0.034973,2.100902,1.0,0.000984,1.018990,0.553748,0.027429,0.018636,0.073891
24,"frozenset({ electronics, sport})",frozenset({ medicine}),0.013089,0.053695,0.001432,0.109405,2.037509,1.0,0.000729,1.062553,0.515958,0.021911,0.058871,0.068037
25,frozenset({ medicine}),"frozenset({ electronics, sport})",0.053695,0.013089,0.001432,0.026668,2.037509,1.0,0.000729,1.013952,0.538098,0.021911,0.013760,0.068037
26,"frozenset({ computers, sport})","frozenset({ medicine, appliances})",0.039282,0.020741,0.001686,0.042929,2.069722,1.0,0.000872,1.023183,0.537976,0.028907,0.022658,0.062116
27,"frozenset({ computers, medicine})","frozenset({ sport, appliances})",0.016800,0.043367,0.001686,0.100374,2.314514,1.0,0.000958,1.063367,0.577649,0.028835,0.059591,0.069629
28,"frozenset({ computers, appliances})","frozenset({ sport, medicine})",0.104244,0.006997,0.001686,0.016177,2.312099,1.0,0.000957,1.009331,0.633535,0.015393,0.009245,0.128600
29,"frozenset({ sport, medicine})","frozenset({ computers, appliances})",0.006997,0.104244,0.001686,0.241023,2.312099,1.0,0.000957,1.180215,0.571491,0.015393,0.152697,0.128600
30,"frozenset({ sport, appliances})","frozenset({ computers, medicine})",0.043367,0.016800,0.001686,0.038885,2.314514,1.0,0.000958,1.022978,0.593691,0.028835,0.022462,0.069629
31,"frozenset({ medicine, appliances})","frozenset({ computers, sport})",0.020741,0.039282,0.001686,0.081302,2.069722,1.0,0.000872,1.045739,0.527790,0.028907,0.043739,0.062116
32,"frozenset({ computers, country_yard})","frozenset({ sport, appliances})",0.017520,0.043367,0.001963,0.112027,2.583230,1.0,0.001203,1.077322,0.623817,0.033308,0.071773,0.078642
33,"frozenset({ sport, appliances})","frozenset({ computers, country_yard})",0.043367,0.017520,0.001963,0.045257,2.583230,1.0,0.001203,1.029052,0.640672,0.033308,0.028232,0.078642
34,"frozenset({ computers, country_yard})","frozenset({ electronics, appliances})",0.017520,0.040101,0.001479,0.084424,2.105265,1.0,0.000777,1.048409,0.534362,0.026345,0.046174,0.060654
35,"frozenset({ computers, appliances})","frozenset({ electronics, country_yard})",0.104244,0.006786,0.001479,0.014188,2.090805,1.0,0.000772,1.007509,0.582430,0.013501,0.007453,0.116072
36,"frozenset({ electronics, country_yard})","frozenset({ computers, appliances})",0.006786,0.104244,0.001479,0.217955,2.090805,1.0,0.000772,1.145401,0.525280,0.013501,0.126943,0.116072
37,"frozenset({ electronics, appliances})","frozenset({ computers, country_yard})",0.040101,0.017520,0.001479,0.036883,2.105265,1.0,0.000777,1.020105,0.546933,0.026345,0.019709,0.060654
38,"frozenset({ computers, construction})","frozenset({ electronics, appliances})",0.015626,0.040101,0.001743,0.111535,2.781345,1.0,0.001116,1.080402,0.650628,0.032284,0.074418,0.077498
39,"frozenset({ computers, appliances})","frozenset({ electronics, construction})",0.104244,0.007176,0.001743,0.016719,2.329990,1.0,0.000995,1.009706,0.637243,0.015891,0.009612,0.129804
40,"frozenset({ electronics, construction})","frozenset({ computers, appliances})",0.007176,0.104244,0.001743,0.242888,2.329990,1.0,0.000995,1.183122,0.574939,0.015891,0.154779,0.129804
41,"frozenset({ electronics, appliances})","frozenset({ computers, construction})",0.040101,0.015626,0.001743,0.043461,2.781345,1.0,0.001116,1.029100,0.667218,0.032284,0.028277,0.077498
42,"frozenset({ computers, construction})","frozenset({ sport, appliances})",0.015626,0.043367,0.001482,0.094855,2.187263,1.0,0.000805,1.056884,0.551424,0.025773,0.053822,0.064517
43,"frozenset({ sport, appliances})","frozenset({ computers, construction})",0.043367,0.015626,0.001482,0.034178,2.187263,1.0,0.000805,1.019209,0.567415,0.025773,0.018847,0.064517
44,"frozenset({ construction, appliances})",frozenset({ country_yard}),0.029694,0.089966,0.005555,0.187077,2.079428,1.0,0.002884,1.119460,0.534985,0.048685,0.106712,0.124412
45,"frozenset({ country_yard, appliances})",frozenset({ construction}),0.035102,0.074996,0.005555,0.158257,2.110212,1.0,0.002923,1.098915,0.545253,0.053137,0.090012,0.116165
46,frozenset({ construction}),"frozenset({ country_yard, appliances})",0.074996,0.035102,0.005555,0.074073,2.110212,1.0,0.002923,1.042088,0.568769,0.053137,0.040388,0.116165
47,frozenset({ country_yard}),"frozenset({ construction, appliances})",0.089966,0.029694,0.005555,0.061747,2.079428,1.0,0.002884,1.034162,0.570416,0.048685,0.033034,0.124412
48,"frozenset({ computers, construction})","frozenset({ country_yard, appliances})",0.015626,0.035102,0.001156,0.073955,2.106864,1.0,0.000607,1.041956,0.533700,0.023312,0.040266,0.053438
49,"frozenset({ computers, country_yard})","frozenset({ construction, appliances})",0.017520,0.029694,0.001156,0.065962,2.221350,1.0,0.000635,1.038828,0.559628,0.025090,0.037377,0.052439
50,"frozenset({ construction, appliances})","frozenset({ computers, country_yard})",0.029694,0.017520,0.001156,0.038917,2.221350,1.0,0.000635,1.022264,0.566650,0.025090,0.021779,0.052439
51,"frozenset({ country_yard, appliances})","frozenset({ computers, construction})",0.035102,0.015626,0.001156,0.032922,2.106864,1.0,0.000607,1.017885,0.544473,0.023312,0.017570,0.053438

Using the lift to compute association rules causes another problem. The lift is a measure that can be highly inflated when using really rare itemsets. This happens because the denominator is the product of the support measures of the two itemsets. In this situation probably the best strategy is to set minimum threshold values for both the measures.

In [46]:
s_purchases_rules = association_rules(s_purchases, metric="lift", min_threshold=2)
s_purchases_rules = s_purchases_rules[["antecedents", "consequents", "antecedent support",
                                       "consequent support", "support", "confidence", "lift"]]
s_purchases_rules = s_purchases_rules[s_purchases_rules["confidence"] > 0.10]
s_purchases_rules = s_purchases_rules.sort_values("lift", ascending=False)
s_purchases_rules = s_purchases_rules.reset_index(drop=True)
s_purchases_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift
0,"frozenset({ computers, medicine})","frozenset({ electronics, appliances})",0.016800,0.040101,0.001878,0.111776,2.787338
1,"frozenset({ computers, construction})","frozenset({ electronics, appliances})",0.015626,0.040101,0.001743,0.111535,2.781345
2,"frozenset({ computers, country_yard})","frozenset({ sport, appliances})",0.017520,0.043367,0.001963,0.112027,2.583230
3,"frozenset({ electronics, sport})","frozenset({ computers, appliances})",0.013089,0.104244,0.003505,0.267754,2.568525
4,"frozenset({ electronics, furniture})","frozenset({ computers, appliances})",0.005637,0.104244,0.001445,0.256267,2.458333
5,"frozenset({ sport, furniture})","frozenset({ computers, appliances})",0.005618,0.104244,0.001394,0.248183,2.380784
6,"frozenset({ electronics, medicine})","frozenset({ computers, appliances})",0.007675,0.104244,0.001878,0.244681,2.347185
7,"frozenset({ computers, electronics})","frozenset({ sport, appliances})",0.034643,0.043367,0.003505,0.101160,2.332649
8,"frozenset({ electronics, construction})","frozenset({ computers, appliances})",0.007176,0.104244,0.001743,0.242888,2.329990
9,"frozenset({ computers, medicine})","frozenset({ sport, appliances})",0.016800,0.043367,0.001686,0.100374,2.314514
10,"frozenset({ sport, medicine})","frozenset({ computers, appliances})",0.006997,0.104244,0.001686,0.241023,2.312099
11,"frozenset({ country_yard, appliances})",frozenset({ construction}),0.035102,0.074996,0.005555,0.158257,2.110212
12,"frozenset({ computers, electronics, applianc...",frozenset({ medicine}),0.016647,0.053695,0.001878,0.112809,2.100902
13,"frozenset({ electronics, country_yard})","frozenset({ computers, appliances})",0.006786,0.104244,0.001479,0.217955,2.090805
14,"frozenset({ construction, appliances})",frozenset({ country_yard}),0.029694,0.089966,0.005555,0.187077,2.079428
15,"frozenset({ electronics, sport})",frozenset({ medicine}),0.013089,0.053695,0.001432,0.109405,2.037509

### Conclusions

The rules above should suggest possible purchase patterns followed by the users. When an user buys one or more products of the antecedent section / sections, there is a reasonable possibility that he will buy one or more product also of the consequent section / sections.
The advised strategy is set as follows:
- Let's take as an example the first rule, so {computers, medicine} -> {electronics, appliances};
- Let's assume an user has already added to its basket one product from "computers" section and one from "medicine" section;
- After the user adds to the basket this last product, the page should show a fast link to the "electronics" section and one to the "appliances" section.

## Pattern mining on purchases and products

The purpose of this section is to find strong associations between purchases of products, in order to provide an efficient advise policy and encourage the user to buy more products.

In [39]:
with open("frequent_purchases.pkl", "rb") as f:  # "rb" = read binary
    purchases = pickle.load(f)

purchases = pd.DataFrame(purchases)

print("Number of frequent itemsets")
print(len(purchases))

Number of frequent itemsets
524

In [62]:
purchases_rules = association_rules(purchases, metric="confidence", min_threshold=0.4)
purchases_rules = purchases_rules[["antecedents", "consequents", "antecedent support",
                                       "consequent support", "support", "confidence", "lift"]]
print("Association rules with minimum confidence level set to 0.4")
purchases_rules

Association rules with minimum confidence level set to 0.4

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift
0,frozenset({214820261}),frozenset({214820233}),0.005524,0.003407,0.002283,0.413303,121.303101
1,frozenset({214820233}),frozenset({214820261}),0.003407,0.005524,0.002283,0.670046,121.303101
2,frozenset({214716710}),frozenset({214716707}),0.001928,0.003583,0.001212,0.628664,175.455247
3,frozenset({214834880}),frozenset({214834877}),0.010328,0.010419,0.004491,0.434783,41.728123
4,frozenset({214834877}),frozenset({214834880}),0.010419,0.010328,0.004491,0.430983,41.728123
5,frozenset({214834880}),frozenset({214826610}),0.010328,0.009468,0.004924,0.476741,50.353300
6,frozenset({214826610}),frozenset({214834880}),0.009468,0.010328,0.004924,0.520066,50.353300
7,frozenset({214826610}),frozenset({214834877}),0.009468,0.010419,0.004098,0.432836,41.541281
8,"frozenset({214834880, 214834877})",frozenset({214826610}),0.004491,0.009468,0.002371,0.527972,55.764353
9,"frozenset({214834880, 214826610})",frozenset({214834877}),0.004924,0.010419,0.002371,0.481505,46.212300
10,"frozenset({214834877, 214826610})",frozenset({214834880}),0.004098,0.010328,0.002371,0.578544,56.015167
11,frozenset({214833755}),frozenset({214834877}),0.002804,0.010419,0.001510,0.538634,51.695210
12,frozenset({214833755}),frozenset({214826610}),0.002804,0.009468,0.001212,0.432251,45.654291
13,frozenset({214829387}),frozenset({214826610}),0.002789,0.009468,0.001278,0.458333,48.409121
14,frozenset({214829387}),frozenset({214834880}),0.002789,0.010328,0.001206,0.432432,41.868505
15,frozenset({214829387}),frozenset({214834877}),0.002789,0.010419,0.001605,0.575450,55.228675
16,frozenset({214829865}),frozenset({214829861}),0.002299,0.003222,0.001203,0.523224,162.395280
17,frozenset({214829865}),frozenset({214829846}),0.002299,0.003191,0.001049,0.456284,143.012747
18,frozenset({214829885}),frozenset({214829878}),0.006020,0.021332,0.002773,0.460616,21.592854
19,"frozenset({214829885, 214829882})",frozenset({214829878}),0.001548,0.021332,0.001033,0.667343,31.283867
20,frozenset({214829887}),frozenset({214829878}),0.012800,0.021332,0.007289,0.569431,26.693924
21,frozenset({214831948}),frozenset({214829878}),0.007854,0.021332,0.004032,0.513395,24.067046
22,"frozenset({214831948, 214829882})",frozenset({214829878}),0.001737,0.021332,0.001275,0.734177,34.416948
23,frozenset({214831946}),frozenset({214829878}),0.008162,0.021332,0.004491,0.550212,25.792962
24,"frozenset({214831946, 214829882})",frozenset({214829878}),0.001950,0.021332,0.001366,0.700483,32.837426
25,"frozenset({214829887, 214831946})",frozenset({214829878}),0.001526,0.021332,0.001008,0.660494,30.962799
26,frozenset({214829882}),frozenset({214829878}),0.009207,0.021332,0.006089,0.661323,31.001685
27,"frozenset({214829887, 214829882})",frozenset({214829878}),0.002635,0.021332,0.002063,0.783075,36.709195
28,frozenset({214831950}),frozenset({214829885}),0.002933,0.006020,0.002267,0.773019,128.410719
29,frozenset({214835017}),frozenset({214835019}),0.006211,0.008001,0.002654,0.427199,53.390510
30,frozenset({214826990}),frozenset({214835109}),0.006657,0.008560,0.003457,0.519340,60.667860
31,frozenset({214835109}),frozenset({214826990}),0.008560,0.006657,0.003457,0.403888,60.667860
32,frozenset({214829765}),frozenset({214835167}),0.005919,0.008428,0.003850,0.650398,77.166655
33,frozenset({214835167}),frozenset({214829765}),0.008428,0.005919,0.003850,0.456781,77.166655
34,"frozenset({214829765, 214835109})",frozenset({214835167}),0.001366,0.008428,0.001109,0.811494,96.279984
35,"frozenset({214835167, 214835109})",frozenset({214829765}),0.002129,0.005919,0.001109,0.520649,87.956255
36,"frozenset({214836932, 214826990})",frozenset({214835109}),0.001702,0.008560,0.001127,0.662362,77.375306
37,"frozenset({214836932, 214835109})",frozenset({214826990}),0.002113,0.006657,0.001127,0.533432,80.126578
38,frozenset({214838227}),frozenset({214835109}),0.003991,0.008560,0.002449,0.613690,71.689619
39,frozenset({214838227}),frozenset({214826990}),0.003991,0.006657,0.001774,0.444532,66.772880
40,"frozenset({214826990, 214838227})",frozenset({214835109}),0.001774,0.008560,0.001256,0.707965,82.702524
41,"frozenset({214835109, 214838227})",frozenset({214826990}),0.002449,0.006657,0.001256,0.512821,77.030479
42,"frozenset({214829765, 214836924})",frozenset({214835167}),0.001554,0.008428,0.001212,0.779798,92.519370
43,"frozenset({214835167, 214836924})",frozenset({214829765}),0.001881,0.005919,0.001212,0.644407,108.863476
44,frozenset({214839971}),frozenset({214839973}),0.003238,0.006692,0.001322,0.408341,61.020119
45,frozenset({214839977}),frozenset({214839956}),0.001580,0.002751,0.001146,0.725646,263.787276
46,frozenset({214839956}),frozenset({214839977}),0.002751,0.001580,0.001146,0.416667,263.787276
47,frozenset({214837280}),frozenset({214838092}),0.001664,0.002754,0.001228,0.737736,267.876345
48,frozenset({214838092}),frozenset({214837280}),0.002754,0.001664,0.001228,0.445838,267.876345
49,frozenset({214837286}),frozenset({214838092}),0.002299,0.002754,0.001033,0.449454,163.199301
50,frozenset({214844355}),frozenset({214844370}),0.002792,0.005301,0.001244,0.445444,84.033810
51,frozenset({214835428}),frozenset({214835426}),0.002493,0.002343,0.001184,0.474811,202.681958
52,frozenset({214835426}),frozenset({214835428}),0.002343,0.002493,0.001184,0.505362,202.681958
53,frozenset({214846119}),frozenset({214845962}),0.003121,0.003065,0.001809,0.579477,189.068575
54,frozenset({214845962}),frozenset({214846119}),0.003065,0.003121,0.001809,0.590164,189.068575
55,frozenset({214848380}),frozenset({214848337}),0.001890,0.003680,0.001275,0.674419,183.246210
56,frozenset({214716707}),frozenset({214832604}),0.003583,0.002098,0.001539,0.429448,204.723192
57,frozenset({214832604}),frozenset({214716707}),0.002098,0.003583,0.001539,0.733533,204.723192

In [59]:
purchases_rules_no = association_rules(purchases, metric="lift", min_threshold=0.0000000001)
print("Number of association rules with no threshold value")
print(len(purchases_rules_no))
purchases_rules_l = association_rules(purchases, metric="lift", min_threshold=2)
print("Number of patterns with threshold value of the lift set equal to 1.5")
print(len(purchases_rules_l))

Number of association rules with no threshold value
216
Number of patterns with threshold value of the lift set equal to 1.5
216

# Conclusions

In this situation the confidence is a more accurate measure because the lift is highly inflated because the itemsets are not really frequent. This is easily showed by the fact that the number of association rules does not change with or without a normal threshold value for the lift (2 should already be a "good" association).

The advised strategy is to show a link / advertisement for the consequent product / products when the antecedent product / products are added to the basket.

In [63]:
purchases_rules = purchases_rules[["antecedents", "consequents", "antecedent support", "consequent support", "support", "confidence", "lift"]]
mono_associations = purchases_rules[(purchases_rules["antecedents"].apply(len) == 1) & (purchases_rules["consequents"].apply(len) == 1)]
multi_associations = purchases_rules[(purchases_rules["antecedents"].apply(len) > 1) | (purchases_rules["consequents"].apply(len) > 1)]

print(mono_associations.head())
print(multi_associations)

              antecedents             consequents  antecedent support  \
0  frozenset({214820261})  frozenset({214820233})            0.005524
1  frozenset({214820233})  frozenset({214820261})            0.003407
2  frozenset({214716710})  frozenset({214716707})            0.001928
3  frozenset({214834880})  frozenset({214834877})            0.010328
4  frozenset({214834877})  frozenset({214834880})            0.010419

   consequent support   support  confidence        lift
0            0.003407  0.002283    0.413303  121.303101
1            0.005524  0.002283    0.670046  121.303101
2            0.003583  0.001212    0.628664  175.455247
3            0.010419  0.004491    0.434783   41.728123
4            0.010328  0.004491    0.430983   41.728123
                          antecedents             consequents  \
8   frozenset({214834880, 214834877})  frozenset({214826610})
9   frozenset({214834880, 214826610})  frozenset({214834877})
10  frozenset({214834877, 214826610})  frozenset({214834880})
19  frozenset({214829885, 214829882})  frozenset({214829878})
22  frozenset({214831948, 214829882})  frozenset({214829878})
24  frozenset({214831946, 214829882})  frozenset({214829878})
25  frozenset({214829887, 214831946})  frozenset({214829878})
27  frozenset({214829887, 214829882})  frozenset({214829878})
34  frozenset({214829765, 214835109})  frozenset({214835167})
35  frozenset({214835167, 214835109})  frozenset({214829765})
36  frozenset({214836932, 214826990})  frozenset({214835109})
37  frozenset({214836932, 214835109})  frozenset({214826990})
40  frozenset({214826990, 214838227})  frozenset({214835109})
41  frozenset({214835109, 214838227})  frozenset({214826990})
42  frozenset({214829765, 214836924})  frozenset({214835167})
43  frozenset({214835167, 214836924})  frozenset({214829765})

    antecedent support  consequent support   support  confidence        lift
8             0.004491            0.009468  0.002371    0.527972   55.764353
9             0.004924            0.010419  0.002371    0.481505   46.212300
10            0.004098            0.010328  0.002371    0.578544   56.015167
19            0.001548            0.021332  0.001033    0.667343   31.283867
22            0.001737            0.021332  0.001275    0.734177   34.416948
24            0.001950            0.021332  0.001366    0.700483   32.837426
25            0.001526            0.021332  0.001008    0.660494   30.962799
27            0.002635            0.021332  0.002063    0.783075   36.709195
34            0.001366            0.008428  0.001109    0.811494   96.279984
35            0.002129            0.005919  0.001109    0.520649   87.956255
36            0.001702            0.008560  0.001127    0.662362   77.375306
37            0.002113            0.006657  0.001127    0.533432   80.126578
40            0.001774            0.008560  0.001256    0.707965   82.702524
41            0.002449            0.006657  0.001256    0.512821   77.030479
42            0.001554            0.008428  0.001212    0.779798   92.519370
43            0.001881            0.005919  0.001212    0.644407  108.863476

In [ ]:
purchases_rules["pair"] = purchases_rules.apply(
    lambda r: tuple(sorted([
        next(iter(r["antecedents"])),
        next(iter(r["consequents"]))
    ])),
    axis=1
)
pair_counts = purchases_rules["pair"].value_counts()
asymmetric_pairs = pair_counts[pair_counts == 1]
print("Mono-directional relationships")
asymmetric_pairs

pair
(214716707, 214716710)    1
(214826610, 214834877)    1
(214833755, 214834877)    1
(214826610, 214833755)    1
(214826610, 214829387)    1
(214829387, 214834880)    1
(214829387, 214834877)    1
(214829861, 214829865)    1
(214829846, 214829865)    1
(214829878, 214829882)    1
(214829885, 214831950)    1
(214835017, 214835019)    1
(214835109, 214836932)    1
(214826990, 214836932)    1
(214835109, 214838227)    1
(214826990, 214838227)    1
(214839971, 214839973)    1
(214837286, 214838092)    1
(214844355, 214844370)    1
(214848337, 214848380)    1
Name: count, dtype: int64

For an association rule {A} -> {B} that respects the confidence threshold value let's define it as:
- Bi-directional rule: if the relation {B} -> {A} also respects the confidence threshold value;
- Mono-directional rule: if the relation {B} -> {A} does not respect the confidence threshold value.

The last output shows all the mono-directional rules regarding purchases with only one product as antecedent (the first one) and only one product as consequent (the second one). The business strategy of above suggests to show the link / advertisement only when the first product is added to the basket, but another strategy could be implemented for the opposite relation.

Assuming the rule to be {A} -> {B}, let's assume that in general it is really likely to buy the two products together, but the customer is likely to remember to buy product B after buying product A, but not to buy product A after buying product B. After implementing a correct A/B test to check for this hypothesis, an efficient strategy would be to show advertiments for both the directions, in order to increase purchases of the products together, independently of which one is bought first.

## Pattern mining on clicks and products

In [ ]:
with open("frequent_clicks.pkl", "rb") as f:  # "rb" = read binary
    clicks = pickle.load(f)

clicks = pd.DataFrame(clicks)

clicks_rules = association_rules(clicks, metric="confidence", min_threshold=0.2)
print(len(clicks_rules))

In [ ]:
clicks_rules = clicks_rules[["antecedents", "consequents", "antecedent support", "consequent support", "support", "confidence", "lift"]]
mono_associations = clicks_rules[(clicks_rules["antecedents"].apply(len) == 1) & (clicks_rules["consequents"].apply(len) == 1)]
multi_associations = clicks_rules[(clicks_rules["antecedents"].apply(len) > 1) | (clicks_rules["consequents"].apply(len) > 1)]

print(mono_associations.head())
print(multi_associations)

In [ ]:
clicks_rules["pair"] = clicks_rules.apply(
    lambda r: tuple(sorted([
        next(iter(r["antecedents"])),
        next(iter(r["consequents"]))
    ])),
    axis=1
)
pair_counts = clicks_rules["pair"].value_counts()
asymmetric_pairs = pair_counts[pair_counts == 1]
asymmetric_pairs